version: '2'
services:

    secure-messaging-ui:
      restart: always
      build: ${SECURE_MESSAGING_HOME}/secure-messaging-ui
      volumes:
        - ${SECURE_MESSAGING_HOME}/secure-messaging-ui/app:/code/app
      networks:
        - secure-messaging-env
      ports:
           - "5000:5000"
    db:
      image: postgres:9.5
      environment:
        POSTGRES_PASSWORD: rasmessage
        POSTGRES_USER: rasmessage
        POSTGRES_DB: messages
      ports:
        - "5433:5432"
      networks:
        - secure-messaging-env

networks:
  secure-messaging-env:
    driver: bridge
